FROM alpine:latest

RUN apk --update add \
  gcc \
  git \
  libc-dev \
  lua5.1 \
  lua5.1-dev \
  luarocks5.1 \
  make

RUN luarocks-5.1 install luanotify 0.1-1 \
  && luarocks-5.1 install middleclass \
  && luarocks-5.1 install penlight

RUN git clone https://github.com/LuaDist/squish.git
WORKDIR /squish
RUN make install
WORKDIR /
